### ISSUE TITLE
aesthetic improvements

### ISSUE THREAD

**Issue by dhowe** [dhowe/Automachar#8]
doesn't look so great at moment

* as one example, there was a suggestion that traditional and simplified have different colors (there is a pallette.png file checked in -- perhaps yellow and blue would work)

* when loading, and info screen is up, bg should be same color as app

* others tweaks? font, colors, layout...

**Comment by cqx931** [comment]
It would be nice to have an option to toggle off the English translations, though that might not be super urgent for this ELO release.

**Comment by dhowe** [comment]
Indeed. Also the potential for muting. Perhaps these controls could be on the info-dialog? But as you say, low priority

**Comment by cqx931** [comment]
One more thing I noticed when I tried to follow the piece for a while. Even as a Chinese speaker, it's very hard for me to capture the exact moments of sensitive words(if that's not intentional). Cause whenever I noticed that there is a change from simplified to traditional(or vice versa), the change already happened and I have to try to recall from my memory what the last word was...

Also, are all the changes between simplified and traditional triggered by this list of characters?(https://github.com/dhowe/autochar/blob/master/autochar.js#L260) I think I noticed changes on words such as "酒铺" and "洋镐" but none of the characters is on the trigger list.

**Comment by dhowe** [comment]
> One more thing I noticed when I tried to follow the piece for a while. Even as a Chinese speaker, it's very hard for me to capture the exact moments of sensitive words(if that's not intentional). Cause whenever I noticed that there is a change from simplified to traditional(or vice versa), the change already happened and I have to try to recall from my memory what the last word was...

any ideas for how this can be made better ?

> Also, are all the changes between simplified and traditional triggered by this list of characters? I think I noticed changes on words such as "酒铺" and "洋镐" but none of the characters is on the trigger list.

In past versions that is correct, so I'm not sure how that would have happened (in the future, you can always check the console). But I've just now added some code that looks at 'words' rather than just characters, which you can see [here](https://github.com/dhowe/autochar/blob/master/autochar.js#L262)

**Comment by cqx931** [comment]
I took a look at the console, but the traditional/simplified Chinese changing process still seems weird to me. 
The trigger it self does makes sense, but it doesn't seem to be connected to the traditional/simplified Chinese changing process.
As an example:
4)突襲 -> 突袭 
this is a traditional to simplified Chinese transition, but there is no trigger identified in the logger.

Later there is a trigger:
trigger: "書" in "上書" -> simp

but the actual transition happened at
15) 正書 -> 正旦 2s 'starring female role in a Chinese opera' (right, proper, correct / dawn; morning; day)

<img width="298" alt="Screenshot 2020-07-06 at 11 21 18 AM" src="https://user-images.githubusercontent.com/3056154/86610068-d2192500-bf7a-11ea-800f-a6c3e9007da1.png">
